name: Build and upload to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true #not needed
      - name: Build SDist
        run: pipx run build --sdist
      - name: Check metadata
        run: pipx run twine check dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-targz
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true #not needed
      - uses: pypa/cibuildwheel@v2.23.0
        env:
          CIBW_SKIP: pp* cp36-* *-musllinux_x86_64 *_i686
          CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=14.0"
          CIBW_BEFORE_ALL_LINUX: >
            yum -y install wget &&
            yum -y install tar &&
            wget https://mirror.ibcp.fr/pub/gnu/gsl/gsl-2.8.tar.gz &&
            tar -zxvf gsl-2.8.tar.gz &&
            cd gsl-2.8 &&
            ./configure &&
            make &&
            make install &&
            cd ..
          CIBW_BEFORE_ALL_MACOS: >
            brew reinstall gcc &&
            brew install gsl
      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl

  upload_all:
    name: Upload
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
